### ISSUE TITLE
Add connman_widget leads to awesome wm crashing

### ISSUE THREAD

**Issue by Tweetdezweet** [stefano-m/awesome-connman_widget#1]
Hi,
I ran into some installation issues at first when I tried to run luarocks install connman_widget but managed to figure that part out.
However, when I configure awesome as described in the readme, whenever I try to log in (using lightdm window manager), awesome crashes/stops and throws me back to my login screen.

I have tried to find out if and where awesome wm log file is but I have not found it yet.
This is my awesome version info:
```awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.2```

**Comment by stefano-m** [comment]
Hello,

sorry to hear that this is not working for you.

If you get back to the login screen it may be that your whole X server is crashing.

Indeed, it would be very useful if you could post the logs from awesome itself.

If you start awesome automatically at login (and depending on your OS), you could find the logs using `journalctl`.

Also note that the lua code for this plugin was written against lua 5.2 and is known to work with lua 5.3, I don't know about 5.1.

**Comment by stefano-m** [comment]
Hey, I am closing this for lack of feedback. Feel free to reopen if you have more information.

Since you are using Lua 5.1, you are probably affected by stefano-m/lua-dbus_proxy/pull/5
