### ISSUE TITLE
Compilation failure on lua 5.4

### ISSUE THREAD

**Issue by RowAtk** [stefano-m/awesome-connman_widget#2]
Hello,

When attempting to install, the dependency 'connman_dbus' always fails to compile due to:
```
callable.c: In function 'closure_callback':  
callable.c:1237:13: error: too few arguments to function 'lua_resume'  
 1237 |       res = lua_resume (L, NULL, npos);  
      |             ^~~~~~~~~~  
In file included from lgi.h:11,  
                 from callable.c:12:  
/usr/include/lua.h:300:15: note: declared here  
  300 | LUA_API int  (lua_resume)     (lua_State *L, lua_State *from, int narg,  
      |               ^~~~~~~~~~  
make[1]: *** [Makefile:63: callable.o] Error 1  
```

This issue exists in other rocks and apparently is due to a change in lua 5.4

What should I do?

**Comment by stefano-m** [comment]
Hi, the problem you are seeing depends on `lgi` (which is a dependency) as you can see in the error message

```
In file included from lgi.h:11, 
```

Lua 5.4 introduced the following [breaking change](https://www.lua.org/manual/5.4/manual.html#8)

> The function lua_resume has an extra parameter.

That you can see again in the error

```
error: too few arguments to function 'lua_resume'  
```

I suggest that you subscribe to https://github.com/pavouk/lgi/issues/247 to track the progress.

Unfortunately I cannot do anything on this end.

I would suggest that you use Lua 5.3 in the meantime.

**Comment by diamondheadshot** [comment]
sudo luarocks --lua-version 5.3 connman_widget
